"""
ClaimBuster API research service - API client wrapper.

This service identifies and scores checkworthy claims using ClaimBuster API.
It expects an optimized query generated by the orchestrator.
"""
from typing import List, Dict
import requests

from ...config import get_settings
from .constants_news import (
    CLAIMBUSTER_BASE_URL,
    CLAIMBUSTER_SCORE_ENDPOINT,
    CLAIMBUSTER_MIN_SCORE,
    CLAIMBUSTER_TIMEOUT,
    DEFAULT_FACTCHECK_MAX_RESULTS
)

# ============================================================================
# CONSTANTS
# ============================================================================

CLAIMBUSTER_SOURCE_NAME = "ClaimBuster"
CLAIMBUSTER_ACCESS_TYPE = "claim_detection"
CLAIMBUSTER_ACCESS_NOTE = "AI-detected checkworthy claim"
CLAIMBUSTER_SCORE_THRESHOLD_HIGH = 0.7
CLAIMBUSTER_SCORE_THRESHOLD_MEDIUM = 0.5

# ============================================================================
# LOGIC
# ============================================================================


def _get_claim_category(score: float) -> str:
    """
    Categorize claim based on ClaimBuster score.

    Args:
        score: ClaimBuster score (0.0-1.0)

    Returns:
        Category string (High/Medium/Low priority)
    """
    if score >= CLAIMBUSTER_SCORE_THRESHOLD_HIGH:
        return "High priority"
    elif score >= CLAIMBUSTER_SCORE_THRESHOLD_MEDIUM:
        return "Medium priority"
    else:
        return "Low priority"


def score_claim_claimbuster(text: str) -> float:
    """
    Score a single claim for checkworthiness using ClaimBuster.

    Args:
        text: Claim text to evaluate

    Returns:
        Score between 0.0-1.0 (higher = more checkworthy)
    """
    settings = get_settings()
    api_key = settings.claimbuster_api_key

    if not api_key:
        return 0.0

    if not text or len(text.strip()) < 5:
        return 0.0

    try:
        url = CLAIMBUSTER_BASE_URL + CLAIMBUSTER_SCORE_ENDPOINT + text

        headers = {
            "x-api-key": api_key
        }

        response = requests.get(url, headers=headers, timeout=CLAIMBUSTER_TIMEOUT)
        response.raise_for_status()

        data = response.json()

        # Extract score from results
        results = data.get("results", [])
        if results and len(results) > 0:
            return float(results[0].get("score", 0.0))

    except Exception as e:
        print(f"     ❌ ClaimBuster scoring error: {e}")

    return 0.0


def search_claimbuster(
    query: str,
    max_results: int = DEFAULT_FACTCHECK_MAX_RESULTS,
    min_score: float = CLAIMBUSTER_MIN_SCORE
) -> List[Dict[str, str]]:
    """
    Identify checkworthy claims via ClaimBuster API.

    Args:
        query: Text containing potential claims (can be full transcript excerpt)
        max_results: Maximum number of claims to return
        min_score: Minimum checkworthiness score (0.0-1.0)

    Returns:
        List of detected claims with scores and priority levels.

    Note:
        Requires CLAIMBUSTER_API_KEY in environment variables.
        ClaimBuster analyzes text and identifies factual claims worth checking.
    """
    settings = get_settings()
    api_key = settings.claimbuster_api_key

    if not api_key:
        print("[INFO factcheck] ClaimBuster API key not configured, skipping")
        return []

    if not query or len(query.strip()) < 10:
        return []

    print(f"[INFO factcheck] Analyzing with ClaimBuster: '{query[:50]}...'")

    claims = []
    try:
        # Split query into sentences (simple approach)
        sentences = [s.strip() + "." for s in query.split(".") if len(s.strip()) > 10]

        for sentence in sentences[:20]:  # Limit to 20 sentences to avoid rate limits
            score = score_claim_claimbuster(sentence)

            if score >= min_score:
                category = _get_claim_category(score)

                claims.append({
                    "title": f"Claim: {sentence[:100]}",
                    "summary": f"Checkworthiness score: {score:.2f} ({category})\n{sentence}",
                    "url": "",  # ClaimBuster doesn't provide URLs
                    "source": CLAIMBUSTER_SOURCE_NAME,
                    "published": "",
                    "access_type": CLAIMBUSTER_ACCESS_TYPE,
                    "has_full_text": False,
                    "access_note": CLAIMBUSTER_ACCESS_NOTE,
                    "claim_score": score,
                    "claim_priority": category
                })

        # Sort by score descending and limit results
        claims.sort(key=lambda x: x.get("claim_score", 0), reverse=True)
        claims = claims[:max_results]

    except Exception as e:
        print(f"     ❌ ClaimBuster error: {e}")

    print(f"     ✅ Found {len(claims)} checkworthy claims")
    return claims
