"""
ClaimBuster API research service - API client wrapper.

This service identifies and scores checkworthy claims using ClaimBuster API.
It expects an optimized query generated by the orchestrator.
"""
from typing import List, Dict

import httpx

from ...config import get_settings
from ...logger import get_logger
from ..retry import RETRY_STRATEGY
from .constants_news import (
    CLAIMBUSTER_BASE_URL,
    CLAIMBUSTER_SCORE_ENDPOINT,
    CLAIMBUSTER_MIN_SCORE,
    CLAIMBUSTER_TIMEOUT,
    DEFAULT_FACTCHECK_MAX_RESULTS
)

logger = get_logger(__name__)

# ============================================================================
# CONSTANTS
# ============================================================================

CLAIMBUSTER_SOURCE_NAME = "ClaimBuster"
CLAIMBUSTER_ACCESS_TYPE = "claim_detection"
CLAIMBUSTER_ACCESS_NOTE = "AI-detected checkworthy claim"
CLAIMBUSTER_SCORE_THRESHOLD_HIGH = 0.7
CLAIMBUSTER_SCORE_THRESHOLD_MEDIUM = 0.5

# ============================================================================
# LOGIC
# ============================================================================


def _get_claim_category(score: float) -> str:
    """
    Categorize claim based on ClaimBuster score.

    Args:
        score: ClaimBuster score (0.0-1.0)

    Returns:
        Category string (High/Medium/Low priority)
    """
    if score >= CLAIMBUSTER_SCORE_THRESHOLD_HIGH:
        return "High priority"
    elif score >= CLAIMBUSTER_SCORE_THRESHOLD_MEDIUM:
        return "Medium priority"
    else:
        return "Low priority"


@RETRY_STRATEGY
async def score_claim_claimbuster(text: str) -> float:
    """
    Score a single claim for checkworthiness using ClaimBuster.

    Args:
        text: Claim text to evaluate

    Returns:
        Score between 0.0-1.0 (higher = more checkworthy)
    """
    settings = get_settings()
    api_key = settings.claimbuster_api_key

    if not api_key:
        return 0.0

    if not text or len(text.strip()) < 5:
        return 0.0

    try:
        url = CLAIMBUSTER_BASE_URL + CLAIMBUSTER_SCORE_ENDPOINT + text
        headers = {"x-api-key": api_key}

        async with httpx.AsyncClient(timeout=CLAIMBUSTER_TIMEOUT) as client:
            response = await client.get(url, headers=headers)
            response.raise_for_status()
            data = response.json()

        results = data.get("results", [])
        if results:
            return float(results[0].get("score", 0.0))

    except Exception as e:
        logger.error("claimbuster_scoring_error", detail=str(e))

    return 0.0


async def search_claimbuster(
    query: str,
    max_results: int = DEFAULT_FACTCHECK_MAX_RESULTS,
    min_score: float = CLAIMBUSTER_MIN_SCORE
) -> List[Dict[str, str]]:
    """
    Identify checkworthy claims via ClaimBuster API.

    Args:
        query: Text containing potential claims (can be full transcript excerpt)
        max_results: Maximum number of claims to return
        min_score: Minimum checkworthiness score (0.0-1.0)

    Returns:
        List of detected claims with scores and priority levels.

    Note:
        Requires CLAIMBUSTER_API_KEY in environment variables.
        ClaimBuster analyzes text and identifies factual claims worth checking.
    """
    settings = get_settings()
    api_key = settings.claimbuster_api_key

    if not api_key:
        logger.warning("claimbuster_no_api_key")
        return []

    if not query or len(query.strip()) < 10:
        return []

    logger.info("claimbuster_search_start", query_preview=query[:50])

    # Split query into sentences for scoring
    sentences = [s.strip() + "." for s in query.split(".") if len(s.strip()) > 10]

    claims = []
    try:
        for sentence in sentences[:20]:  # Limit to 20 sentences to avoid rate limits
            score = await score_claim_claimbuster(sentence)

            if score >= min_score:
                category = _get_claim_category(score)
                claims.append({
                    "title": f"Claim: {sentence[:100]}",
                    "summary": f"Checkworthiness score: {score:.2f} ({category})\n{sentence}",
                    "url": "",
                    "source": CLAIMBUSTER_SOURCE_NAME,
                    "published": "",
                    "access_type": CLAIMBUSTER_ACCESS_TYPE,
                    "has_full_text": False,
                    "access_note": CLAIMBUSTER_ACCESS_NOTE,
                    "claim_score": score,
                    "claim_priority": category
                })

        claims.sort(key=lambda x: x.get("claim_score", 0), reverse=True)
        claims = claims[:max_results]

    except Exception as e:
        logger.error("claimbuster_error", detail=str(e))

    logger.info("claimbuster_search_end", claims_count=len(claims))
    return claims
