"""
Google Fact Check API research service - API client wrapper.

This service searches fact-check claims via Google Fact Check Tools API.
It expects an optimized query generated by the orchestrator.
"""
from typing import List, Dict
import requests

from ...config import get_settings
from .constants_news import (
    GOOGLE_FACTCHECK_BASE_URL,
    GOOGLE_FACTCHECK_DEFAULT_LANGUAGE,
    GOOGLE_FACTCHECK_MAX_RESULTS,
    GOOGLE_FACTCHECK_TIMEOUT,
    DEFAULT_FACTCHECK_MAX_RESULTS
)

# ============================================================================
# CONSTANTS
# ============================================================================

FACTCHECK_SOURCE_PREFIX = "Google Fact Check"
FACTCHECK_ACCESS_TYPE = "fact_check"
FACTCHECK_ACCESS_NOTE = "Fact-check claim - external link"

# ============================================================================
# LOGIC
# ============================================================================


def search_google_factcheck(
    query: str,
    max_results: int = DEFAULT_FACTCHECK_MAX_RESULTS
) -> List[Dict[str, str]]:
    """
    Search fact-checked claims via Google Fact Check Tools API.

    Args:
        query: Optimized search query (claim text)
        max_results: Maximum number of results (max 10)

    Returns:
        List of fact-check claims with title, rating, url, source, date.

    Note:
        Requires GOOGLE_FACTCHECK_API_KEY in environment variables.
        Returns claims that have been fact-checked by verified organizations.
    """
    settings = get_settings()
    api_key = settings.google_factcheck_api_key

    if not api_key:
        print("[INFO factcheck] Google Fact Check API key not configured, skipping")
        return []

    if not query or len(query.strip()) < 3:
        return []

    print(f"[INFO factcheck] Searching Google Fact Check: '{query}'")

    claims = []
    try:
        params = {
            "key": api_key,
            "query": query,
            "languageCode": GOOGLE_FACTCHECK_DEFAULT_LANGUAGE,
            "pageSize": min(max_results, GOOGLE_FACTCHECK_MAX_RESULTS)
        }

        response = requests.get(
            GOOGLE_FACTCHECK_BASE_URL,
            params=params,
            timeout=GOOGLE_FACTCHECK_TIMEOUT
        )
        response.raise_for_status()

        data = response.json()

        if "claims" in data:
            for claim in data.get("claims", [])[:max_results]:
                # Extract first review (most relevant)
                reviews = claim.get("claimReview", [])
                if not reviews:
                    continue

                review = reviews[0]
                publisher = review.get("publisher", {})

                # Build summary from claim + rating
                claim_text = claim.get("text", "")
                rating = review.get("textualRating", "Unknown")
                summary = f"Claim: {claim_text}\nRating: {rating}"

                claims.append({
                    "title": claim.get("claimant", "Unknown") + ": " + claim_text[:100],
                    "summary": summary,
                    "url": review.get("url", ""),
                    "source": f"{FACTCHECK_SOURCE_PREFIX} - {publisher.get('name', 'Unknown')}",
                    "published": review.get("reviewDate", "")[:10],  # YYYY-MM-DD
                    "access_type": FACTCHECK_ACCESS_TYPE,
                    "has_full_text": False,
                    "access_note": FACTCHECK_ACCESS_NOTE,
                    "rating": rating
                })
        else:
            error = data.get("error", {})
            print(f"     ❌ Google Fact Check error: {error.get('message', 'Unknown error')}")

    except requests.exceptions.RequestException as e:
        print(f"     ❌ Google Fact Check request error: {e}")
    except Exception as e:
        print(f"     ❌ Google Fact Check error: {e}")

    print(f"     ✅ Found {len(claims)} fact-checked claims")
    return claims
