"""
GNews research service - API client wrapper.

This service searches news articles via GNews API (alternative to NewsAPI).
It expects an optimized query generated by the orchestrator.
"""
from typing import List, Dict

import httpx

from ...config import get_settings
from ...logger import get_logger
from ..retry import RETRY_STRATEGY
from .constants_news import (
    GNEWS_BASE_URL,
    GNEWS_DEFAULT_LANGUAGE,
    GNEWS_DEFAULT_SORT,
    GNEWS_MAX_RESULTS_FREE,
    GNEWS_TIMEOUT,
    DEFAULT_NEWS_MAX_RESULTS
)

logger = get_logger(__name__)


@RETRY_STRATEGY
async def search_gnews(
    query: str,
    max_results: int = DEFAULT_NEWS_MAX_RESULTS
) -> List[Dict[str, str]]:
    """
    Search news articles via GNews API.

    Args:
        query: Optimized search query (keywords, phrases)
        max_results: Maximum number of results (max 10 for free tier)

    Returns:
        List of articles with title, description, url, source, date.

    Note:
        Requires GNEWS_API_KEY in environment variables.
        Free tier limitations: 100 requests/day, max 10 articles per request

    Raises:
        httpx.HTTPStatusError: On HTTP 5xx / 429 after retries
        httpx.TimeoutException: On timeout after retries
    """
    settings = get_settings()
    api_key = settings.gnews_api_key

    if not api_key:
        logger.warning("gnews_no_api_key")
        return []

    if not query or len(query.strip()) < 3:
        return []

    logger.info("gnews_search_start", query_preview=query[:50])

    params = {
        "q": query,
        "token": api_key,
        "lang": GNEWS_DEFAULT_LANGUAGE,
        "max": min(max_results, GNEWS_MAX_RESULTS_FREE),
        "sortby": GNEWS_DEFAULT_SORT
    }

    async with httpx.AsyncClient(timeout=GNEWS_TIMEOUT) as client:
        response = await client.get(GNEWS_BASE_URL, params=params)
        response.raise_for_status()
        data = response.json()

    articles = []
    if "articles" in data:
        for article in data.get("articles", [])[:max_results]:
            articles.append({
                "title": article.get("title", "No title"),
                "summary": article.get("description", ""),
                "url": article.get("url", ""),
                "source": f"GNews - {article.get('source', {}).get('name', 'Unknown')}",
                "published": article.get("publishedAt", "")[:10],
                "access_type": "news_article",
                "has_full_text": False,
                "access_note": "News article - external link"
            })
    else:
        error_msg = data.get("errors", ["Unknown error"])[0] if "errors" in data else "Unknown error"
        logger.error("gnews_error", message=error_msg)

    logger.info("gnews_search_end", articles_count=len(articles))
    return articles
