"""
GNews research service - API client wrapper.

This service searches news articles via GNews API (alternative to NewsAPI).
It expects an optimized query generated by the orchestrator.
"""
from typing import List, Dict
import requests

from ...config import get_settings
from .constants_news import (
    GNEWS_BASE_URL,
    GNEWS_DEFAULT_LANGUAGE,
    GNEWS_DEFAULT_SORT,
    GNEWS_MAX_RESULTS_FREE,
    GNEWS_TIMEOUT,
    DEFAULT_NEWS_MAX_RESULTS
)


def search_gnews(
    query: str,
    max_results: int = DEFAULT_NEWS_MAX_RESULTS
) -> List[Dict[str, str]]:
    """
    Search news articles via GNews API.

    Args:
        query: Optimized search query (keywords, phrases)
        max_results: Maximum number of results (max 10 for free tier)

    Returns:
        List of articles with title, description, url, source, date.

    Note:
        Requires GNEWS_API_KEY in environment variables.
        Free tier limitations: 100 requests/day, max 10 articles per request
    """
    settings = get_settings()
    api_key = settings.gnews_api_key

    if not api_key:
        print("[INFO news] GNews API key not configured, skipping GNews")
        return []

    if not query or len(query.strip()) < 3:
        return []

    print(f"[INFO news] Searching GNews: '{query}'")

    articles = []
    try:
        params = {
            "q": query,
            "token": api_key,
            "lang": GNEWS_DEFAULT_LANGUAGE,
            "max": min(max_results, GNEWS_MAX_RESULTS_FREE),
            "sortby": GNEWS_DEFAULT_SORT
        }

        response = requests.get(GNEWS_BASE_URL, params=params, timeout=GNEWS_TIMEOUT)
        response.raise_for_status()

        data = response.json()

        if "articles" in data:
            for article in data.get("articles", [])[:max_results]:
                articles.append({
                    "title": article.get("title", "No title"),
                    "summary": article.get("description", ""),
                    "url": article.get("url", ""),
                    "source": f"GNews - {article.get('source', {}).get('name', 'Unknown')}",
                    "published": article.get("publishedAt", "")[:10],  # YYYY-MM-DD
                    "access_type": "news_article",
                    "has_full_text": False,
                    "access_note": "News article - external link"
                })
        else:
            error_msg = data.get("errors", ["Unknown error"])[0] if "errors" in data else "Unknown error"
            print(f"     ❌ GNews error: {error_msg}")

    except requests.exceptions.RequestException as e:
        print(f"     ❌ GNews request error: {e}")
    except Exception as e:
        print(f"     ❌ GNews error: {e}")

    print(f"     ✅ Found {len(articles)} GNews articles")
    return articles
