"""
NewsAPI research service - API client wrapper.

This service searches recent news articles via NewsAPI.
It expects an optimized query generated by the orchestrator.
"""
from typing import List, Dict
import requests
from datetime import datetime, timedelta

from ...config import get_settings
from .constants_news import (
    NEWSAPI_BASE_URL,
    NEWSAPI_DEFAULT_LANGUAGE,
    NEWSAPI_DEFAULT_SORT,
    NEWSAPI_MAX_RESULTS_FREE,
    NEWSAPI_MAX_DAYS_BACK_FREE,
    NEWSAPI_TIMEOUT,
    DEFAULT_NEWS_MAX_RESULTS,
    DEFAULT_NEWS_DAYS_BACK
)


def search_newsapi(
    query: str,
    max_results: int = DEFAULT_NEWS_MAX_RESULTS,
    days_back: int = DEFAULT_NEWS_DAYS_BACK
) -> List[Dict[str, str]]:
    """
    Search news articles via NewsAPI.

    Args:
        query: Optimized search query (keywords, phrases)
        max_results: Maximum number of results (max 100 for free tier)
        days_back: Number of days to search back (max 30 for free tier)

    Returns:
        List of articles with title, description, url, source, date.

    Note:
        Requires NEWSAPI_KEY in environment variables.
        Free tier limitations: 100 requests/day, 30 days history
    """
    settings = get_settings()
    api_key = settings.newsapi_key

    if not api_key:
        print("[INFO news] NewsAPI key not configured, skipping NewsAPI")
        return []

    if not query or len(query.strip()) < 3:
        return []

    print(f"[INFO news] Searching NewsAPI: '{query}'")

    articles = []
    try:
        # Calculate date range
        to_date = datetime.now()
        from_date = to_date - timedelta(days=min(days_back, NEWSAPI_MAX_DAYS_BACK_FREE))

        params = {
            "q": query,
            "apiKey": api_key,
            "language": NEWSAPI_DEFAULT_LANGUAGE,
            "sortBy": NEWSAPI_DEFAULT_SORT,
            "pageSize": min(max_results, NEWSAPI_MAX_RESULTS_FREE),
            "from": from_date.strftime("%Y-%m-%d"),
            "to": to_date.strftime("%Y-%m-%d")
        }

        response = requests.get(NEWSAPI_BASE_URL, params=params, timeout=NEWSAPI_TIMEOUT)
        response.raise_for_status()

        data = response.json()

        if data.get("status") == "ok":
            for article in data.get("articles", [])[:max_results]:
                # Skip articles without description
                if not article.get("description"):
                    continue

                articles.append({
                    "title": article.get("title", "No title"),
                    "summary": article.get("description", ""),
                    "url": article.get("url", ""),
                    "source": f"NewsAPI - {article.get('source', {}).get('name', 'Unknown')}",
                    "published": article.get("publishedAt", "")[:10],  # YYYY-MM-DD
                    "access_type": "news_article",
                    "has_full_text": False,
                    "access_note": "News article - external link"
                })
        else:
            print(f"     ❌ NewsAPI error: {data.get('message', 'Unknown error')}")

    except requests.exceptions.RequestException as e:
        print(f"     ❌ NewsAPI request error: {e}")
    except Exception as e:
        print(f"     ❌ NewsAPI error: {e}")

    print(f"     ✅ Found {len(articles)} NewsAPI articles")
    return articles
