"""
NewsAPI research service - API client wrapper.

This service searches recent news articles via NewsAPI.
It expects an optimized query generated by the orchestrator.
"""
from typing import List, Dict
import requests
from datetime import datetime, timedelta

from ...config import get_settings
from ...logger import get_logger

logger = get_logger(__name__)
from .constants_news import (
    NEWSAPI_BASE_URL,
    NEWSAPI_DEFAULT_LANGUAGE,
    NEWSAPI_DEFAULT_SORT,
    NEWSAPI_MAX_RESULTS_FREE,
    NEWSAPI_MAX_DAYS_BACK_FREE,
    NEWSAPI_TIMEOUT,
    DEFAULT_NEWS_MAX_RESULTS,
    DEFAULT_NEWS_DAYS_BACK
)


def search_newsapi(
    query: str,
    max_results: int = DEFAULT_NEWS_MAX_RESULTS,
    days_back: int = DEFAULT_NEWS_DAYS_BACK
) -> List[Dict[str, str]]:
    """
    Search news articles via NewsAPI.

    Args:
        query: Optimized search query (keywords, phrases)
        max_results: Maximum number of results (max 100 for free tier)
        days_back: Number of days to search back (max 30 for free tier)

    Returns:
        List of articles with title, description, url, source, date.

    Note:
        Requires NEWSAPI_KEY in environment variables.
        Free tier limitations: 100 requests/day, 30 days history
    """
    settings = get_settings()
    api_key = settings.newsapi_key

    if not api_key:
        logger.warning("newsapi_no_api_key")
        return []

    if not query or len(query.strip()) < 3:
        return []

    logger.info("newsapi_search_start", query_preview=query[:50])

    articles = []
    try:
        # Calculate date range
        to_date = datetime.now()
        from_date = to_date - timedelta(days=min(days_back, NEWSAPI_MAX_DAYS_BACK_FREE))

        params = {
            "q": query,
            "apiKey": api_key,
            "language": NEWSAPI_DEFAULT_LANGUAGE,
            "sortBy": NEWSAPI_DEFAULT_SORT,
            "pageSize": min(max_results, NEWSAPI_MAX_RESULTS_FREE),
            "from": from_date.strftime("%Y-%m-%d"),
            "to": to_date.strftime("%Y-%m-%d")
        }

        response = requests.get(NEWSAPI_BASE_URL, params=params, timeout=NEWSAPI_TIMEOUT)
        response.raise_for_status()

        data = response.json()

        if data.get("status") == "ok":
            for article in data.get("articles", [])[:max_results]:
                # Skip articles without description
                if not article.get("description"):
                    continue

                articles.append({
                    "title": article.get("title", "No title"),
                    "summary": article.get("description", ""),
                    "url": article.get("url", ""),
                    "source": f"NewsAPI - {article.get('source', {}).get('name', 'Unknown')}",
                    "published": article.get("publishedAt", "")[:10],  # YYYY-MM-DD
                    "access_type": "news_article",
                    "has_full_text": False,
                    "access_note": "News article - external link"
                })
        else:
            logger.error("newsapi_error", message=data.get('message', 'Unknown error'))

    except requests.exceptions.RequestException as e:
        logger.error("newsapi_error", detail=str(e))
    except Exception as e:
        logger.error("newsapi_error", detail=str(e))

    logger.info("newsapi_search_end", articles_count=len(articles))
    return articles
