/**
 * Module Cookies - Extraction des cookies YouTube
 */

/**
 * Extrait les cookies YouTube de l'utilisateur
 * @returns {Promise<string>} - Cookies au format Netscape
 */
export async function getYouTubeCookies() {
    try {
        // Récupérer tous les cookies YouTube
        const cookies = await chrome.cookies.getAll({
            domain: '.youtube.com'
        });

        if (!cookies || cookies.length === 0) {
            return null;
        }

        // Convertir au format Netscape (format attendu par yt-dlp)
        const netscapeCookies = cookies.map(cookie => {
            const domain = cookie.domain.startsWith('.') ? cookie.domain : '.' + cookie.domain;
            const flag = cookie.hostOnly ? 'FALSE' : 'TRUE';
            const path = cookie.path || '/';
            const secure = cookie.secure ? 'TRUE' : 'FALSE';
            const expiration = cookie.expirationDate ? Math.floor(cookie.expirationDate) : '0';
            const name = cookie.name;
            const value = cookie.value;

            return `${domain}\t${flag}\t${path}\t${secure}\t${expiration}\t${name}\t${value}`;
        });

        // Ajouter l'en-tête Netscape
        const header = '# Netscape HTTP Cookie File\n# This file was generated by Chrome Extension\n';
        return header + netscapeCookies.join('\n');

    } catch (error) {
        console.error('Erreur lors de l\'extraction des cookies:', error);
        return null;
    }
}
